#!/usr/bin/env python2.7

import socket
import sys
import getopt
import thread
import re

HOST = "140.113.235.151"
PORT = 55677

sock = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
sock.bind((HOST,PORT))
sock.listen(10)

users = []
mbox = {}

def quotesHandler(quoteschk):
    islegal = 0
    quoteclose = False

    for i in range(0,len(quoteschk)):
        if quoteschk[i]=='\"' and quoteclose == False:
            quoteclose = True
        elif quoteschk[i]==' ' and quoteclose == True:
            quoteschk = quoteschk[:i]+'^'+quoteschk[i+1:]
        elif quoteschk[i]=='\"' and quoteclose == True:
            quoteclose = False
    while quoteschk[-1:] == ' ':
        quoteschk = quoteschk[:-1]
    return quoteschk, islegal

def shell(s,addr):
    while True:
        data = s.recv(2048)
        data, legalstate = quotesHandler(data)
        commandlist = data.split()
        command = commandlist[0]
        commandlist.pop(0)

        if command == "exit":
            s.sendall("exit\n")
            s.close
            break
        s.sendall("Hello\n")

while True:
    addr = (HOST, PORT)
    connection, address = sock.accept()
    thread.start_new_thread(shell,(connection,address))
